### PR TITLE
Fix Add CW20 Token (Cosmwasm v1)

### LINKED ISSUE #133: Add token - feature=cosmwasm enabled
Currently in JUNO chain, I have this error:
image

### PR DESCRIPTION
**Pull request by giansalex**
close #133 
image

### CODE REVIEW

**Comment by giansalex** [comment]
Missing `TOKEN` to run `Test Unit`
https://github.com/chainapsis/keplr-extension/blob/79d7b67db28dc143ec51e8239c77bb663fc08c30/.github/workflows/test.yml#L14

**Comment by Thunnini** [comment]
Is there an open CosmWasm testnet we could test this on? What would be the best way to go about the testing process?

**Comment by giansalex** [comment]
@Thunnini yes, Juno Testnet 
- [discord](https://discord.gg/D6vUj85x) (you can get tokens in faucet channel)
- Endpoints: 
rpc: `https://rpc.juno.omniflix.co`
lcd: `https://api.juno.omniflix.co`
- [App](https://giansalex.github.io/juno-cw20/) to `suggestChain`.

cw20 contract addresses:
- `juno14vhcdsyf83ngsrrqc92kmw8q9xakqjm0ff2dpn` (NTN)
- `juno12dnl585uxzddjw9hw4ca694f054shgpg48pnqn` (PER)

**Review by nwood719 — APPROVED** [review]

**Comment by zlounes** [comment]
Is there a problem with this PR? We are looking forward for this PR integrated, so we can use it with the JunoMint application. Thanks in advance

**Pull request merged**
