### PR TITLE
fix[config]: config for cyber

### PR DESCRIPTION
**Pull request by dimakorzhovnik**
when creating tx keplr was white, after changed feeCurrencies for cyber in the config, all right

### CODE REVIEW

**Comment by Thunnini** [comment]
What version of Keplr are you using? Also, could you show me the error message that shows up in the console for the blank page when you send the tx?

Cyber's feeCurrencies being empty is intentional. Cyber doesn't use fees, so it is left empty–and Keplr is currently designed where it works without fees when feeCurrencies is empty.

**Comment by dimakorzhovnik** [comment]
v0.8.5


I have cloned repository and change the config, run build keplr, and used local build, wasn't mistakes

Sometimes need to run chrome://flags/#enable-webassembly

**Comment by dimakorzhovnik** [comment]
v0.8.5


I have cloned repository and change config, run build keplr and used local build, wasn't mistakes

Sometimes need to run chrome://flags/#enable-webassembly

**Comment by litvintech** [comment]
@Thunnini Hello. Please, merge this issue because keplr not work at all with cyber.page in latest releases of keplr if fee not set.

**Comment by Thunnini** [comment]
Cyber not having a fee currency is intentional. Because the Cyber chain doesn’t need tx fees, there is not fee currency–which will hide the fee buttons. However, I think there may have been issues handling a signature requested from a webpage. I believe the commit above should solve the issue, and will be included in the next release.

**Pull request closed without merging**
