### PR TITLE
Feature: Allow transactions to supply their own fee

### PR DESCRIPTION
**Pull request by clockworkgr**
This PR handles the case where a transaction to be signed using the Keplr-supplied offline signer has a fee already set.

The supplied fee is displayed to the user in the signing screen with a warning that it was set by the calling application already and an option to switch to the Keplr fee selection buttons to override it.

I am unfamiliar with mobx so not sure I have approached the local-state handling of the details tab component the right way.

Please let me know if any adjustements/changes are needed.

### CODE REVIEW

**Comment by clockworkgr** [comment]
Regarding the last commit (https://github.com/chainapsis/keplr-extension/pull/109/commits/d41ef3b8bea65c9e64f9ad8f4d65ec70103d883e)

If fee is not set or ignored, payer and granter are undfined/null as they should be. However due to the way the proto data is marshalled and unmarshalled , if the fee IS set and not ignored (as is the case for this PR) payer and granter are set to the empty string which is then marshalled leading to an unexpected 4 extra bytes in the serialized Tx and the node will fail in signature verification.

The commit ensures that if fee is not set or set but payer/granter not explicitly set, they will be properly nulled in serialisation.

**Comment by Thunnini** [comment]
@clockworkgr Hi , I’ve reviewed the PR and it appears that if the requested sign doc has a fee it doesn’t show the fee button, and only shows the fee button when the sign doc has empty fees. However, these changes may have issues with webpages that have already integrated Keplr.

My suggestion is to provide an option within the Keplr API where you can explicitly state that you do not want to set your fees on Keplr. For CosmJS usage, we can set something like keplr:prefer_no_set_fee at the end of the memo, and Keplr can recognize this as an option and return a memo without the keplr:prefer_no_set_fee back to the webpage.

**Comment by clockworkgr** [comment]
Wouldn't it be better/preferrable (if possible) to set it via an exposed method? i.e. have the default as is and provide something like:

`window.keplr.preferNoSetFee(true)`

**Comment by Thunnini** [comment]
Thanks for the report on the proto-related bug. In regards to the fee, I’ll try to unblock you ASAP.

**Comment by Thunnini** [comment]
@clockworkgr I will go ahead and merge and let you know when the implementation is complete. We can merge for now and find the way to handle the ‘preferNoSetFee’ option later. I will let you know before we cut a release

**Pull request merged**
